### PR TITLE
Reduce log level for the missing player statistic exceptions

### PR DESCRIPTION
**Pull request by mingnz**
Was spamming the server logs with warnings for a warning we don't really care about. Remove those warnings from this fork.

### CODE REVIEW

**Comment by mingnz** [comment]
The better approach is to change the log levels but I'm not familiar enough with Java to do this...

**Comment by danieljimeneznz** [comment]
https://github.com/spark-64/minecraft-prometheus-exporter/blob/d41eb22550aa867d0cfb7cb008606d9ee9a210bb/src/main/java/de/sldk/mc/PrometheusExporter.java#L14

Somewhere here try doing - if you don't care about warns
```
getLogger().setLevel(Level.SEVERE)
```

cc @spark-ming

**Comment by mingnz** [comment]
> https://github.com/spark-64/minecraft-prometheus-exporter/blob/d41eb22550aa867d0cfb7cb008606d9ee9a210bb/src/main/java/de/sldk/mc/PrometheusExporter.java#L14
> 
> Somewhere here try doing - if you don't care about warns
> 
> ```
> getLogger().setLevel(Level.SEVERE)
> ```
> 
> cc @spark-ming

This could work, will need to test it out some time.

**Review by danieljimeneznz — CHANGES_REQUESTED** [review]
Actually thought, you could just downgrade these to debug via `logger.debug()`, and then use the setLevel to `LEVEL.INFO`

**Comment by mingnz** [comment]
Downgrading log level works perfect. It's default to info so don't need to set that. Fine is kinda like debug for this logger.

**Review by danieljimeneznz — APPROVED** [review]
I've never seen`fine` as a log level 😆

**Comment by mingnz** [comment]
@danieljimeneznz wait until you see the log level `finer`

**Pull request merged**
